import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  form: {
    padding: 20,
  },
  label: {
    fontSize: 14,
    color: '#444',
    marginBottom: 6,
    marginLeft: 2,
  },
  input: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 10,
    paddingLeft: 10,
    borderRadius: 10,
    fontSize: 16,
    textAlignVertical: 'center',
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
    marginTop: 10,
  },
  dates: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
    marginTop: 10,
  },
  dateLabelsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    gap: 50, // TODO: improve this solution - not good for other device sizes
  },
  dateLabel: {
    flex: 1,
    textAlign: 'center',
    color: '#444',
    fontSize: 14,
    marginBottom: 6,
  },
  datePickersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dateHyphen: {
    width: 24,
    textAlign: 'center',
    color: '#999',
    paddingBottom: 12,
    fontSize: 18,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 16,
    alignItems: 'center',
  },
  metaColumn: {
    flex: 1,
  },
  metaColumnNarrow: {
    width: 56,
  },
  metaLabel: {
    fontSize: 14,
    color: '#444',
    marginBottom: 6,
    marginLeft: 2,
  },
  metaInput: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 1,
    paddingLeft: 10,
    borderRadius: 10,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  priorityBox: {
    width: 56,
    height: 45,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  priorityDropdown: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    minWidth: 200,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  dropdownTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  priorityOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 2,
  },
  priorityOptionSelected: {
    backgroundColor: '#e3f2fd',
  },
  priorityOptionText: {
    fontSize: 16,
    color: '#666',
    marginLeft: 12,
    fontWeight: '500',
  },
  priorityOptionTextSelected: {
    color: '#1976d2',
    fontWeight: 'bold',
  },
});
